// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT98QDjvAYYAJqnP611jCcEY79Iv3uF1g',
    appId: '1:755737951099:web:8395e22a34a130552e1bde',
    messagingSenderId: '755737951099',
    projectId: 'dailo-2a3b8',
    authDomain: 'dailo-2a3b8.firebaseapp.com',
    storageBucket: 'dailo-2a3b8.firebasestorage.app',
    measurementId: 'G-17SMQF8QE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyz61MRyZc7EX6Z2uqWAq7ZMqVTNYFS9M',
    appId: '1:755737951099:android:cd8070863bc7f7cb2e1bde',
    messagingSenderId: '755737951099',
    projectId: 'dailo-2a3b8',
    storageBucket: 'dailo-2a3b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4VNXT1dUwzFH6vL6dY6p9IpS4Sy7YGs',
    appId: '1:755737951099:ios:c5fcf3f3e242b47d2e1bde',
    messagingSenderId: '755737951099',
    projectId: 'dailo-2a3b8',
    storageBucket: 'dailo-2a3b8.firebasestorage.app',
    iosBundleId: 'com.example.dialo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4VNXT1dUwzFH6vL6dY6p9IpS4Sy7YGs',
    appId: '1:755737951099:ios:c5fcf3f3e242b47d2e1bde',
    messagingSenderId: '755737951099',
    projectId: 'dailo-2a3b8',
    storageBucket: 'dailo-2a3b8.firebasestorage.app',
    iosBundleId: 'com.example.dialo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT98QDjvAYYAJqnP611jCcEY79Iv3uF1g',
    appId: '1:755737951099:web:296fd3e72e4f2e102e1bde',
    messagingSenderId: '755737951099',
    projectId: 'dailo-2a3b8',
    authDomain: 'dailo-2a3b8.firebaseapp.com',
    storageBucket: 'dailo-2a3b8.firebasestorage.app',
    measurementId: 'G-6MJ0YKKFLS',
  );
}
